# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ma-dev-preBuild - Pre-Build, Lint and Test

on:
  pull_request:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ma-dev-app # set this to your application's name

jobs:
  lint_test_and_build:
    name: Lint, Test and Build
    environment: preBuild
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      working-directory: ${{GITHUB.WORKSPACE}}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm package installation
        shell: cmd
        run: |
          cd "${{ env.working-directory }}"
          npm install

      - name: npm linting
        shell: cmd
        run: |
          cd "${{ env.working-directory }}"
          npm run lint

      - name: npm build
        # npm run test --if-present
        # Below command works for linux
        # NODE_ENV=production REACT_APP_ENV_REGION=${{vars.REACT_APP_ENV_REGION}} REACT_APP_GOOGLE_CLIENT_ID=${{vars.REACT_APP_GOOGLE_CLIENT_ID}} REACT_APP_HOSTED_URL=${{vars.REACT_APP_HOSTED_URL}} npm run build --release
        # Below command is required for Windows command prompt only
        shell: cmd
        run: |
          cd "${{ env.working-directory }}"
          set NODE_ENV=production 
          set VITE_REACT_APP_GOOGLE_CLIENT_ID=${{vars.VITE_REACT_APP_GOOGLE_CLIENT_ID}}
          set VITE_REACT_APP_HOSTED_URL=${{vars.VITE_REACT_APP_HOSTED_URL}}
          set VITE_REACT_APP_MITTARV_ONLY=${{vars.VITE_REACT_APP_MITTARV_ONLY}}
          set VITE_REACT_APP_AES_ENCRYPTION_KEY=${{vars.VITE_REACT_APP_AES_ENCRYPTION_KEY}}
          set VITE_REACT_APP_NODE_ENV=${{vars.VITE_REACT_APP_NODE_ENV}}
          set VITE_REACT_APP_AES_CBC_32_LENGTH_SYMMETRIC_ENCRYPTION_KEY=${{vars.VITE_REACT_APP_AES_CBC_32_LENGTH_SYMMETRIC_ENCRYPTION_KEY}}
          npm run build --release
